### ISSUE TITLE
Make the Notes input 15-lines high by default please

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#10]
Everyone likes a little space to compose their thoughts ;)
![2](https://user-images.githubusercontent.com/16148220/39946032-4b8ff02a-5575-11e8-857f-f3b4f65d553d.jpg)

**Comment by tmonzur** [comment]
Updated.

**Comment by tmonzur** [comment]
![15 lines in height](https://user-images.githubusercontent.com/38818306/40281081-64fb7aa6-5c7e-11e8-90de-e0fc1d06a9f1.png)
