### ISSUE TITLE
Enabled on CMS & Waves but not working on either yet

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#13]
At the moment it just shows "Edit" on all pages and clicking that doesn't open any modals. Sorry, let me know when ready to test.

**Comment by tmonzur** [comment]
Yes the edit will work after complete the point#5.

I am preparing the table edit feature like you share with me a reference link.

**Comment by BostNisReport** [comment]
To be clear, this particular ticket refers to the Admin Toolbar dropdown text link, which will have 3 x possible text: "Add" (when no record yet exists), "Edit" (when a record exists and the user is an Admin), "View" (when a record exist and the user is logged in (except Customers who should not see anything anyway).

**Comment by tmonzur** [comment]
i understand you point. But in case of "edit" we can do the edit from the list table.

Another point regarding "Edit", when admin logged in and come to any page what was edit in previous by more than one administrator, in that case with the edit button what will be the function, please clear little bit more. 

For non administrator better we will remove the drop-down and i already did that. non-administrator user only can see the status menu with color of the icon.

**Comment by tmonzur** [comment]
Updated.

**Comment by tmonzur** [comment]
![view only for non administrator user](https://user-images.githubusercontent.com/38818306/40281818-c142859e-5c87-11e8-835b-14a71864bdf4.png)
![after add it display color and also display edit menu](https://user-images.githubusercontent.com/38818306/40281823-cdf17444-5c87-11e8-94dc-442ee46f9bd3.png)

**Comment by tmonzur** [comment]
![edit popup will display modal form with content](https://user-images.githubusercontent.com/38818306/40281854-03f971fe-5c88-11e8-8cb8-68ffb005a63a.png)
