### ISSUE TITLE
Please remove all trace from non-Administrator users on the frontend

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#14]
We have this lying around in our shop page possibly followed by a fatal error...

        <div id="ex1" class="modal" style="display:none;">
            <div class="modal-info">
                <div id="nds_form_feedback" style="margin-bottom:10px; text-align:center;"></div>
                <form method="post" id="nds_add_user_meta_ajax_form" action="https://dev.waves.agentdesign.co.uk/wp-admin/admin-post.php">
                    <p>Status:<br>
                        <select id="status_color" name="status_color">
                            <option value="ffffff">Default - White</option>
                            <option value="2331e9">Ongoing - Blue</option>
                            <option value="c311e9">To-Do - Purple</option>
                            <option value="e4eb17">In Development - Yellow</option>
                            <option value="e3951b">In Progress - Orange</option>
                            <option value="59b61b">Done - Green</option>
                            <option value="e91a37">Warning - Red</option>
                        </select>
                    </p>
                    <p>Assignee:<br>                
                        <select id="assignee" name="assignee">

**Comment by tmonzur** [comment]
Updated.

**Comment by tmonzur** [comment]
![admin-status plugin code not display on shop page](https://user-images.githubusercontent.com/38818306/40281779-4a7e0be0-5c87-11e8-960f-090362dc51a1.png)
