### ISSUE TITLE
Clicking save empties the form and shows default values, it should not

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#15]
When saving, the success message should show but the fields should remain populated as saved:
![1](https://user-images.githubusercontent.com/16148220/40248510-d07df576-5ad8-11e8-82f8-38f93983467e.jpg)

**Comment by tmonzur** [comment]
![general settings waves wordpress](https://user-images.githubusercontent.com/38818306/40357847-38698746-5ddf-11e8-89be-dac1559f9030.png)

**Comment by BostNisReport** [comment]
This works, but as reported here #16(last comment), we have some issues with character encoding.
I just added:

Testing a new string.
Let's see how it work, all fine?

and when saving I get:

![1](https://user-images.githubusercontent.com/16148220/40378814-41b63790-5dfd-11e8-9229-93fedaff9bd7.jpg)

when closing the modal I see

![2](https://user-images.githubusercontent.com/16148220/40378854-5817fdd4-5dfd-11e8-946f-d736905368c1.jpg)

on page reload

![3](https://user-images.githubusercontent.com/16148220/40378883-6a97d736-5dfd-11e8-9a50-cf17a61732a4.jpg)

We need to have this fixed.

**Comment by tmonzur** [comment]
Updated...
