### ISSUE TITLE
Saved values do not save

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#16]
https://dev.waves.agentdesign.co.uk/wp-admin/options-general.php?page=setupstatus

When clicking Save I am not getting anything saved. What can I do, this is not complete I am afraid.
Let me know when work is complete.

**Comment by tmonzur** [comment]
Its work fine..
![screenshot 2018-05-21 04 05 52](https://user-images.githubusercontent.com/38818306/40284142-503cb872-5cac-11e8-8456-b5bf7ec48d7f.png)

**Comment by BostNisReport** [comment]
Save values are saved now, but edit modal does not close on save, not sure this is how it has to work, and some values like commas, are translated into html encoded character values %2C.

I added a return carriage and this string

Test , ; : & % 

which on save becomes: 

Test %2C %3B %3A %26 %25

The return carriage get lost, and what is worst, saving again changes the latter string into:

Test %252C %253B %253A %2526 %2525

and saving again

Test %25252C %25253B %25253A %252526 %252525

![1](https://user-images.githubusercontent.com/16148220/40378326-e85348ce-5dfb-11e8-9f73-b6ccc0077a86.jpg)

**Comment by tmonzur** [comment]
![plugins waves wordpress 1](https://user-images.githubusercontent.com/38818306/40444889-69700186-5eec-11e8-8b94-6b53ccec347b.png)

**Comment by BostNisReport** [comment]
first sight I can see there is still an escaped char industry\'s
![issue16-1](https://user-images.githubusercontent.com/16148220/40450882-9e5ab49c-5ee5-11e8-8e2d-c5dc55c4ec5a.jpg)

The Action column with the EDIT field is missing.
Anyways, re saving that note adds others \ chars and the return carriages get lost.

![issue16-12jpg](https://user-images.githubusercontent.com/16148220/40450914-b73df884-5ee5-11e8-8fd7-96252a4f3216.jpg)

This seems a different plugin version from the one installed on dev.waves.

**Comment by tmonzur** [comment]
Updated.
