### ISSUE TITLE
"Admin Setup Status" interferes with "WP Nav Menu Cache" adding inline display: none;

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#17]
Found a bug on this page:
https://dev.waves.agentdesign.co.uk/wp-admin/options-general.php?page=wp_nav_menu_cache 
"WP Nav Menu Cache" shows its content as hidden

![1](https://user-images.githubusercontent.com/16148220/40334427-71375a72-5d66-11e8-82ec-68cc84b43b1f.jpg)

with #wp_nav_menu_cache which has display: none; inlined.

**Comment by BostNisReport** [comment]
![2](https://user-images.githubusercontent.com/16148220/40334445-900c6398-5d66-11e8-88fe-ebf36f915965.jpg)

This comes from Admin Setup Status plugin, deactivating it fixes.

Please check this out and verify the potential conflict, and if exist fix it.
Also make a check on the rest of the wp-admin to be sure that this is not happening on other pages.

**Comment by BostNisReport** [comment]
There are also a couple of console errors related to
https://dev.waves.agentdesign.co.uk/wp-content/plugins/setupstatus//assets/js/jquery.min.js

![1](https://user-images.githubusercontent.com/16148220/40334503-d23da6be-5d66-11e8-8787-4e5f2cdc9a43.jpg)

**Comment by tmonzur** [comment]
Its ok now..
