### ISSUE TITLE
Conflicts with "WP Real Categories Management"

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#18]
Sorry, I can't have it active with this conflict.

For example the Category Tree doesn't show while this is active: https://dev.waves.agentdesign.co.uk/wp-admin/edit.php?post_type=documentation
And one conflict I have found worries me about others I have now.
So, please, please work out whatever causes this and make sure it is impossible to happen anywhere else.

**Comment by tmonzur** [comment]
![documentation waves wordpress](https://user-images.githubusercontent.com/38818306/40358062-e1fdcf24-5ddf-11e8-9d13-5119cad09452.png)
