### ISSUE TITLE
Change "Edit" to "Add" when a record doesn't exist for a page

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#2]

**Comment by tmonzur** [comment]
if user "a" worked on seting-1
then in database must will have record
in that case when user "b" want to do work 
then why we will edit that message. 

------- let me know your thoughts.

**Comment by BostNisReport** [comment]
The status is a shared communication method among a number of users, all working as a team. The status is for the page and is the same for all users.

**Comment by tmonzur** [comment]
Done.

**Comment by tmonzur** [comment]
![after add it display color and also display edit menu](https://user-images.githubusercontent.com/38818306/40278692-ccf9f690-5c57-11e8-9de4-0da6c4ec093a.png)

**Comment by tmonzur** [comment]
![after add it display under setting list page](https://user-images.githubusercontent.com/38818306/40278724-4b40c38a-5c58-11e8-8845-83e7bcc18618.png)
