### ISSUE TITLE
Add a 1px grey border to the colour icon so that we can see the white one

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#3]
https://andriy.dev.waves.agentdesign.co.uk/wp-admin/options-general.php?page=setupstatus

![1](https://user-images.githubusercontent.com/16148220/39944936-2dee8058-5571-11e8-9d4c-2c1837052c76.jpg)
![2](https://user-images.githubusercontent.com/16148220/39944931-28260376-5571-11e8-9c20-e4f38806ccbd.jpg)

**Comment by tmonzur** [comment]
Updated..

**Comment by tmonzur** [comment]
![color with 2px border](https://user-images.githubusercontent.com/38818306/40278915-be66125e-5c5b-11e8-9c64-2fb8243090e0.png)
