### ISSUE TITLE
Make the Page Title in the "Page Name" column a ling to the page.

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#4]
https://andriy.dev.waves.agentdesign.co.uk/wp-admin/options-general.php?page=setupstatus

Which means the "VIEW" link becomes unnecessary and can be removed.

**Comment by tmonzur** [comment]
Updated.

**Comment by tmonzur** [comment]
![link with page name to go to the edit page](https://user-images.githubusercontent.com/38818306/40280727-892f1e1e-5c79-11e8-8f0d-ff0659fc50e3.png)
