### ISSUE TITLE
Change "VIEW" to "Edit" and make the rows editable like "Shortcode Content Variables"

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#5]
https://andriy.dev.waves.agentdesign.co.uk/wp-admin/options-general.php?page=setupstatus

https://andriy.dev.waves.agentdesign.co.uk/wp-admin/themes.php?page=scv

**Comment by tmonzur** [comment]
Prepared the row editable on popup, and also after change by popup all area will be updated automatically too.

**Comment by tmonzur** [comment]
![admin settings status waves wordpress](https://user-images.githubusercontent.com/38818306/40307451-66f29654-5d24-11e8-9d8b-b13a2a8bb491.png)
