### ISSUE TITLE
Remove "Notes" from the dropdown. Edit does the same thing, shows the note it is editable then anyway.

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#7]

**Comment by tmonzur** [comment]
Updated.

**Comment by tmonzur** [comment]
![remove note from the dropdown menu with edit menu](https://user-images.githubusercontent.com/38818306/40278925-f7ead8ca-5c5b-11e8-8067-7eb7e29a581e.png)
