### ISSUE TITLE
Admin Menu icon isn't changing back to grey when going to a page that doesn't have a status record set yet

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#8]

**Comment by BostNisReport** [comment]
For example: https://andriy.dev.waves.agentdesign.co.uk/wp-admin/options-writing.php

**Comment by tmonzur** [comment]
You mean the setup status icon color only will display color on reference pages? 
Suppose, administrator now working on woocommerce settings page. But Editor did some work on that page. In that case when admin will check the woocommerce setting page what will display the color of setup status icon???

**Comment by BostNisReport** [comment]
The status icon just shows the latest status colour. If it changes, it changes. One page = one status = one colour icon. Don't over-think it, I don't think I can make it any simpler ;)

**Comment by tmonzur** [comment]
Updated.

**Comment by tmonzur** [comment]
![page has no status and colored in grey](https://user-images.githubusercontent.com/38818306/40280991-36411dc0-5c7d-11e8-8b5a-03230562002b.png)
![page has status and colored with that](https://user-images.githubusercontent.com/38818306/40280992-36764630-5c7d-11e8-8764-e453e6328c5e.png)
