### ISSUE TITLE
Assignee also needs to be a list of "Administrators".

### ISSUE THREAD

**Issue by BostNisReport** [wgoldm/admin-setup-status#9]
Assignee also needs to be a list of "Administrators".
However, now you have added a list of "Roles", I can think of some uses for that.
So, can you add a dropdown and record for selecting an "Administrator" user as well please.

![1](https://user-images.githubusercontent.com/16148220/39945087-d0018778-5571-11e8-995c-7ccf400c5e07.jpg)

**Comment by tmonzur** [comment]
Updated.

**Comment by tmonzur** [comment]
![list of all admin users](https://user-images.githubusercontent.com/38818306/40281037-e27c77d8-5c7d-11e8-92ce-b138721c7e97.png)
